# -*- coding: utf-8 -*-
"""tensorflow_project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xICFDBS30uy0kpLmq-37CXjD8o2ZwXgE
"""

import cv2
import numpy as np
import os
import zipfile
from google.colab.patches import cv2_imshow
import tensorflow as tf
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

data = pd.read_csv('ggl.csv')
data.head()

data.shape

data.drop('symbol', axis=1, inplace=True)

data['date'] = pd.to_datetime(data['date'], utc=True)
data #it makes data column object to the date type

data.info()

data.sort_values('date')

data['date'] = data['date'].dt.strftime('%Y-%m-%d')

DF = data.copy()
DF['date'] = pd.to_datetime(DF['date'])
# Set 'date' column as index
DF = DF.set_index('date')
DF

DF.drop(columns =['adjClose','adjHigh','adjLow','adjOpen','adjVolume','divCash','splitFactor'] , inplace=True)
DF

DF['high'].plot(label='High', color='green')

plt.title('High')
plt.xlabel('Date')
plt.ylabel('Value')
plt.legend()
plt.show()

DF['low'].plot(label='Low', color='blue')

plt.title('Low')
plt.xlabel('Date')
plt.ylabel('Value')
plt.legend()
plt.show()

plt.scatter(DF['high'], DF['volume'])
plt.xlabel('High val')
plt.ylabel('Volume')
plt.show()

training_set = DF[:'2020'].iloc[:,0:1].values
test_set = DF['2020':].iloc[:,0:1].values
training_set

DF['close'][:'2020'].plot(figsize=(16,4),legend=True)
DF['close']['2020':].plot(figsize=(16,4),legend=True, color = 'r')
plt.legend(['Training set (Before 2020)','Test set (2020 and beyond)'], fontsize=12)
plt.title('Google stock price', fontsize=16)
plt.show()

from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range=(0,1))
training_set_scaled = sc.fit_transform(training_set)
training_set_scaled

timesteps = 60

X_train = []
y_train = []
for i in range(timesteps,1147):
    X_train.append(training_set_scaled[i-timesteps:i,0])
    y_train.append(training_set_scaled[i,0])
X_train, y_train = np.array(X_train), np.array(y_train)
X_train.shape

X_train = np.reshape(X_train, (X_train.shape[0],X_train.shape[1],1))
X_train.shape

dataset_total = pd.concat((DF['close'][:'2020'], DF['close']['2020':]),axis=0)
inputs = dataset_total[len(dataset_total)-len(test_set) - 60:].values
inputs = inputs.reshape(-1,1)
inputs  = sc.transform(inputs)

X_test = []
for i in range(timesteps, len(inputs)):
    X_test.append(inputs[i-timesteps:i,0])
X_test = np.array(X_test)
X_test = np.reshape(X_test, (X_test.shape[0],X_test.shape[1],1))

from tensorflow import keras
from tensorflow.keras import layers
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout

Model = Sequential()
Model.add(LSTM(units = 100, return_sequences = True, input_shape = (X_train.shape[1],1)))
Model.add(Dropout(0.2))
Model.add(LSTM(units = 100, return_sequences = True))
Model.add(Dropout(0.2))
Model.add(LSTM(units = 100, return_sequences = True))
Model.add(Dropout(0.2))

Model.add(layers.LSTM(units = 100, return_sequences = False))
Model.add(layers.Dropout(rate = 0.2))
Model.add(layers.Dense(units = 25))
Model.add(layers.Dense(units = 1))
Model.add(Dense(units = 1))

Model.summary()

from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

early_stopping = EarlyStopping(monitor='val_loss', min_delta=0.03, patience=5, restore_best_weights=True)
model_checkpoint = ModelCheckpoint('best_model.h5', save_best_only=True)

Model.compile(optimizer= 'adam', loss = 'mean_squared_error', metrics =['accuracy'])

epochs = 15
batch_size = 32

history =  Model.fit(X_train, y_train, epochs = epochs, batch_size = batch_size, callbacks=[early_stopping, model_checkpoint])

predicted_stock_price = Model.predict(X_test)
predicted_stock_price = sc.inverse_transform(predicted_stock_price)#returning back form scaling 0-1

def plot_predictions(test,predicted):
    plt.plot(test, color='red',label='Real Google Stock Price')
    plt.plot(predicted, color='blue',label='Predicted Google Stock Price')
    plt.title('Google Stock Price Prediction')
    plt.xlabel('Time')
    plt.ylabel('Google Stock Price')
    plt.legend()
    plt.show()

plot_predictions(test_set, predicted_stock_price)

