# -*- coding: utf-8 -*-
"""turkey_car_market_analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HW_mK2HojeBxRkTe_p_5oSglYJNy-GMe
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('turkey_car_market.csv')
df.head()

df.shape

df.describe()

df.info()

df['Marka'].unique()

df['Arac Tip Grubu'].unique()

df['Arac Tip'].unique()

df = df.dropna(subset=['Model Yıl'])

df['Model Yıl'] = df['Model Yıl'].astype(str).str.split('.').str[0].astype(int)

df.head()

df.isna().sum()

nan_row = df[df.isnull().any(axis=1)]
print(nan_row)

df = df.drop(85)
df = df.reset_index(drop=True)

df.isna().sum()

from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder(handle_unknown='ignore')

encoded_df = pd.DataFrame(enc.fit_transform(df[['Marka']]).toarray(), columns=enc.get_feature_names_out(['Marka']))
df = pd.concat([df, encoded_df], axis=1)

df.head()

df.drop(columns=['Marka', 'Arac Tip'], inplace= True)

df.head()

round(pd.pivot_table(data = df, columns = "Model Yıl", values = "Fiyat")).T

from sklearn.preprocessing import MinMaxScaler
min_max_scaler = MinMaxScaler()

min_max_scaler.fit(df[['Model Yıl']])
df_scaled = min_max_scaler.transform(df[['Model Yıl']])
df['Model Yılı'] = df_scaled

df.drop(columns=['Model Yıl'], inplace= True)
df.head()

df['CCM'].unique()

ccm_dic = {'1801-2000 cc': 1900, '1301-1600 cc': 1450, '1601-1800 cc': 1700, '1300 cc ve altı': 1200,
       '2501-3000 cc': 2750, 'Bilmiyorum': np.nan, '2001-2500 cc': 2250, '4001-4500 cc': 4250}

df['CCM'] = df['CCM'].map(ccm_dic)

df.head()

mean = df['CCM'].mean()
df['CCM'] = df['CCM'].fillna(mean)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_ccm = scaler.fit_transform(df['CCM'].values.reshape(-1, 1))
df['scaled_ccm'] = scaled_ccm

df.head()

df.drop(columns=['CCM'], inplace=True)
df.head()

df['Kimden'].unique()

per_dic = {'Galeriden': 1, 'Sahibinden': 0, 'Yetkili': 1}
df['Kimden'] = df['Kimden'].map(per_dic)

df['Kimden'].unique()

stat_dic = {'2. El': 1, '0 km': 0}
df['Durum'] = df['Durum'].map(stat_dic)

df.head()

scaled_km = scaler.fit_transform(df['Km'].values.reshape(-1, 1))
df['Km'] = scaled_km

df.head()

df['Vites'].unique()

vit_dic = {'Otomatik Vites': 2, 'Yarı Otomatik Vites': 1, 'Düz Vites': 0}
df['Vites'] = df['Vites'].map(vit_dic)

df['Beygir Gucu'].unique()

bey_dic = {'176-200 BG': 185, '101-125 BG': 117, '76-100 BG': 85, '151-175 BG': 167,
       '100 BG ve altı': 70, '201-225 BG': 217, '126-150 BG': 137, 'Bilmiyorum': np.nan,
       '276-300 BG': 287, '226-250 BG': 237}
df['Beygir Gucu'] = df['Beygir Gucu'].map(bey_dic)

mean = df['Beygir Gucu'].mean()
df['Beygir Gucu'] = df['Beygir Gucu'].fillna(mean)

scaled_bey = scaler.fit_transform(df['Beygir Gucu'].values.reshape(-1, 1))
df['Beygir Gucu'] = scaled_bey

df.head()

